DROP TABLE PRAEMIE;
DROP TABLE KIND;
DROP TABLE MASCHINE;
DROP TABLE PERSONAL;
DROP TABLE ABTEILUNG;
DROP TABLE GEHALT;

CREATE TABLE GEHALT (
  GEH_STUFE VARCHAR(5) PRIMARY KEY,
  BETRAG INT
);

CREATE TABLE ABTEILUNG (
  ABT_NR VARCHAR(5) PRIMARY KEY,
  NAME VARCHAR(30)
);

CREATE TABLE PERSONAL (
  PNR INT PRIMARY KEY,
  VORNAME VARCHAR(20),
  NACHNAME VARCHAR(20),
  GEH_STUFE VARCHAR(5),
  ABT_NR VARCHAR(5),
  KRANKENKASSE VARCHAR(3),
  FOREIGN KEY (GEH_STUFE) REFERENCES GEHALT(GEH_STUFE),
  FOREIGN KEY (ABT_NR) REFERENCES ABTEILUNG(ABT_NR)
);

CREATE TABLE MASCHINE (
  MNR INT PRIMARY KEY,
  NAME VARCHAR(20),
  PNR INT,
  ANSCH_DATUM DATE,
  NEUWERT INT,
  ZEITWERT INT,
  FOREIGN KEY (PNR) REFERENCES PERSONAL(PNR)
);

CREATE TABLE KIND (
  PNR INT,
  K_NAME VARCHAR(20),
  K_VORN VARCHAR(20),
  K_GEB DATE,
  PRIMARY KEY (PNR, K_VORN, K_NAME),
  FOREIGN KEY (PNR) REFERENCES PERSONAL(PNR)
);

CREATE TABLE PRAEMIE (
  PNR INT,
  P_BETRAG INT,
  DATUM DATE,
  PRIMARY KEY (PNR, P_BETRAG, DATUM),
  FOREIGN KEY (PNR) REFERENCES PERSONAL(PNR)
);

INSERT INTO ABTEILUNG VALUES ('abt11', 'Verwaltung');
INSERT INTO ABTEILUNG VALUES ('abt12', 'Projektierung');
INSERT INTO ABTEILUNG VALUES ('abt13', 'Produktion');
INSERT INTO ABTEILUNG VALUES ('abt14', 'Lagerung');
INSERT INTO ABTEILUNG VALUES ('abt15', 'Verkauf');
INSERT INTO ABTEILUNG VALUES ('abt16', 'Forschung');

INSERT INTO GEHALT VALUES ('it1', 2523);
INSERT INTO GEHALT VALUES ('it2', 2873);
INSERT INTO GEHALT VALUES ('it3', 3027);
INSERT INTO GEHALT VALUES ('it4', 3341);
INSERT INTO GEHALT VALUES ('it5', 3782);

INSERT INTO PERSONAL VALUES (123, 'Ada', 'Lovelace', 'it5', 'abt13', 'dek');
INSERT INTO PERSONAL VALUES (124, 'Leonhard', 'Euler', 'it2', 'abt11', 'aok');
INSERT INTO PERSONAL VALUES (126, 'Rene', 'Descartes', 'it1', 'abt12', 'bak');
INSERT INTO PERSONAL VALUES (127, 'Alan', 'Turing', 'it2', 'abt14', 'dek');
INSERT INTO PERSONAL VALUES (132, 'Grace', 'Hopper', 'it4', 'abt15', 'dek');
INSERT INTO PERSONAL VALUES (145, 'Marie', 'Curie', 'it4', 'abt15', 'aok');
INSERT INTO PERSONAL VALUES (147, 'Hedy', 'Lamarr', 'it5', 'abt11', 'tkk');
INSERT INTO PERSONAL VALUES (133, 'Radia', 'Perlman', 'it3', 'abt12', 'tkk');
INSERT INTO PERSONAL VALUES (161, 'Martin', 'Fowler', 'it2', 'abt13', 'dek');
INSERT INTO PERSONAL VALUES (163, 'Erich', 'Gamma', 'it1', 'abt14', 'aok');
INSERT INTO PERSONAL VALUES (164, 'Marlyn', 'Meltzer', 'it4', 'abt13', 'bak');
INSERT INTO PERSONAL VALUES (173, 'Richard', 'Helm', 'it1', NULL, 'dek');
INSERT INTO PERSONAL VALUES (177, 'Linus', 'Torvalds', 'it2', 'abt11', 'dek');

INSERT INTO MASCHINE VALUES (1, 'Bohrmaschine', 123, '01-FEB-14', 30000, 15000);
INSERT INTO MASCHINE VALUES (2, 'Bohrmaschine', 124, '01-JULY-07', 30000, 18000);
INSERT INTO MASCHINE VALUES (3, 'Hobelmaschine', 161, '01-JAN-07', 40000, 10000);
INSERT INTO MASCHINE VALUES (11, 'Drehbank', 145, '01-MAR-09', 29000, 19000);
INSERT INTO MASCHINE VALUES (12, 'Hobelmaschine', 126, '01-APR-09', 31000, 21000);
INSERT INTO MASCHINE VALUES (14, 'Bohrmaschine', 126, '01-SEP-11', 32000, 22000);
INSERT INTO MASCHINE VALUES (21, 'Drehbank', 133, '01-OCT-12', 32000, 23000);
INSERT INTO MASCHINE VALUES (23, 'Lochcomputer', 123, '01-NOV-14', 31000, 25000);

INSERT INTO KIND VALUES (123, 'Lovelace', 'Lotta', '13-JULY-14');
INSERT INTO KIND VALUES (123, 'Lovelace', 'Maria', '13-AUG-12');
INSERT INTO KIND VALUES (127, 'Pitts', 'Smalltalk', '25-MAR-05');
INSERT INTO KIND VALUES (133, 'Perlman', 'Ron', '06-SEP-08');
INSERT INTO KIND VALUES (161, 'Fowler', 'John', '09-AUG-10');
INSERT INTO KIND VALUES (163, 'Gamma', 'Berta', '22-DEC-07');
INSERT INTO KIND VALUES (177, 'Torvalds', 'Tux', '01-JAN-13');

INSERT INTO PRAEMIE VALUES (123, 700, '22-DEC-07');
INSERT INTO PRAEMIE VALUES (124, 500, '21-FEB-14');
INSERT INTO PRAEMIE VALUES (133, 600, '03-NOV-09');
INSERT INTO PRAEMIE VALUES (161, 500, '22-APR-11');
INSERT INTO PRAEMIE VALUES (145, 500, '22-APR-11');
INSERT INTO PRAEMIE VALUES (132, 1000, '18-JUNE-13');
INSERT INTO PRAEMIE VALUES (123, 2300, '09-JULY-14');
INSERT INTO PRAEMIE VALUES (124, 200, '01-SEP-15');
INSERT INTO PRAEMIE VALUES (147, 400, '28-OCT-07');

/** Aufgabe 5.1 **/

INSERT INTO KIND VALUES (145, 'Curie', 'Pierre','01-NOV-15');

INSERT INTO PERSONAL VALUES (188, 'Linus', 'Pauling', 'it3', 'abt15', 'aok');

INSERT INTO PERSONAL VALUES (199, 'Jade', 'Reymond', 'it5', 'abt13', 'tkk');

INSERT INTO MASCHINE VALUES (30, 'Kettensaege', 199, '20-NOV-15', 2000, 1900);


INSERT INTO PRAEMIE VALUES (132, 300, '01-NOV-15');
INSERT INTO PRAEMIE VALUES (145, 300, '01-NOV-15');
INSERT INTO PRAEMIE VALUES (188, 300, '01-NOV-15');

/**Aufgabe 5.2**/


CREATE TABLE Maschinen_Reparatur (
  MNR INT,
  Rep_DATUM DATE,
  Rep_Kosten INT,
  PNR INT,
  Rep_Erklaerung VARCHAR(50),
  
  PRIMARY KEY (MNR, PNR, Rep_DATUM),
  FOREIGN KEY (MNR) REFERENCES MASCHINE(MNR),
  FOREIGN KEY (PNR) REFERENCES Personal(PNR)
);


INSERT INTO Maschinen_Reparatur VALUES (1, '23-MAY-15', 50, 173, 'Bohrkopf ausgewechselt' );
INSERT INTO Maschinen_Reparatur VALUES (12, '27-FEB-12', 2500, 132, 'Motorreparatur und Reinigung' );
INSERT INTO Maschinen_Reparatur VALUES (30, '01-NOV-15', 200, 133, 'Tank undicht, ausgetauscht' );

/** Aufgabe 5.3**/



/** Geben Sie fuer jeden Mitarbeiter,
der mindestens zwei Praemien erhalten hat,
die Personalnummer und die Summe der Praemien an.**/


SELECT PRAEMIE.PNR,COUNT(PRAEMIE.PNR), SUM(PRAEMIE.P_BETRAG)
FROM PRAEMIE
GROUP BY PNR
HAVING COUNT(PNR) >1;




 
/**Geben Sie alle Mitarbeiter aus, deren Kinder nach 2010 geboren sind.**/

SELECT *
FROM KIND
Where K_GEB > '01-JAN-11' ;

/**Geben Sie alle Mitarbeiter aus, die Mitglied bei der AOK sind.**/
SELECT *
FROM PERSONAL
WHERE KRANKENKASSE = 'aok';

/**Geben Sie alle Abteilungen aus,
die Mitarbeiter mit der Gehaltsstufe 'it5' haben.**/
SELECT ABT_NR
FROM  PERSONAL
WHERE GEH_STUFE = 'it5';

/**Geben Sie alle Abteilungen aus,
deren Mitarbeiter zusammen mehr als 6.000 EUR Monatsgehalt haben.**/

SELECT PERSONAL.ABT_NR 
FROM PERSONAL, GEHALT 
WHERE PERSONAL.GEH_STUFE = GEHALT.GEH_STUFE
GROUP BY ABT_NR
HAVING SUM(BETRAG) > 6000;






/**Geben Sie alle Maschinen aus,
die nur noch weniger als die Haelfte ihres Neuwerts wert sind.**/
SELECT *
FROM MASCHINE
WHERE Zeitwert < (Neuwert/2);


/**Geben Sie alle Mitarbeiter aus,
die weniger als 3000 EUR im Monat verdienen.**/

SELECT PERSONAL.PNR, PERSONAL.VORNAME, PERSONAL.NACHNAME
FROM PERSONAL, GEHALT
WHERE PERSONAL.GEH_STUFE = GEHALT.GEH_STUFE AND GEHALT.BETRAG < 3000;

/*Eine weitere Moeglichkeit*/
SELECT PERSONAL.PNR, PERSONAL.VORNAME, PERSONAL.NACHNAME
FROM PERSONAL JOIN GEHALT ON PERSONAL.GEH_STUFE = GEHALT.GEH_STUFE 
AND GEHALT.BETRAG < 3000;



/**Bezogen auf g.): Wenn es eine Gehaltserhoehung um 15% geben wurde,
welche Mitarbeiter waeren das dann?**/

SELECT PERSONAL.PNR, PERSONAL.VORNAME, PERSONAL.NACHNAME
FROM PERSONAL, GEHALT
WHERE PERSONAL.GEH_STUFE = GEHALT.GEH_STUFE
AND (GEHALT.BETRAG*1.15) < 3000;





/** Geben Sie alle Maschinen aus, die von Mitarbeitern bedient werden,
die in einer Abteilung arbeiten, die mit P anfaengt. **/

SELECT MASCHINE.NAME, MASCHINE.MNR
FROM MASCHINE, PERSONAL, ABTEILUNG
WHERE MASCHINE.PNR = PERSONAL.PNR
AND PERSONAL.ABT_NR = ABTEILUNG.ABT_NR
AND ABTEILUNG.NAME LIKE 'P%';



/**Geben Sie den Namen des Mitarbeiters und der Maschinen aus,
die schon einmal repariert wurden**/

SELECT DISTINCT(MASCHINE.NAME), PERSONAL.VORNAME, PERSONAL.NACHNAME
FROM MASCHINEN_REPARATUR,PERSONAL,MASCHINE
WHERE MASCHINE.MNR = MASCHINEN_REPARATUR.MNR
AND PERSONAL.PNR = MASCHINEN_REPARATUR.PNR;
